#!/bin/bash
# Remplace les espace dans les noms de fichier par un '_'

for a in * ;do
  b=$(echo $a | sed -e 's/[[:blank:]]/_/g');
  if [ -e "$b" ];then
  echo "">/dev/null;
  else
  mv "$a" "$b";
  fi
done
